### ISSUE TITLE
new order

### ISSUE THREAD

**Issue by HansenBurger** [HansenBurger/Luckycloudlab#2]
### 摘要
修改团队和学术成果的格式，填充研究工作和主页的内容

### 团队页面修改
保留上一个版本四个老师的格式，做成可点击阅览区分层级的个人介绍

### 学术成果的修改和填充
1. 内容的字体放大1-2个px
2. 文字颜色加深(黑色
3. 突出序号，改变换行的缩进间距(具体值未定
4. 补充新论文(未收集 

### 研究工作补充
根据现有的资料生成post文档

### 图床
以获得允许

### 优先级
1. 学术成果的修改和填充
2. 研究工作补充
3. 团队页面修改
4. 图床

**Comment by nyameteor** [comment]
学术成果的修改和填充
- [x] 内容的字体放大1-2个px
- [x] 文字颜色加深(黑色
- [x] 突出序号，改变换行的缩进间距(具体值未定
- [x] 补充新论文(未收集

**Comment by HansenBurger** [comment]
ALL done
